---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional@16.2.1"]

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [-w]
        files: ^.*\.(md|py|jinja|yaml|sh|yml)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    # Otherwise will fail on commit-msg hook
    hooks:
      - id: prettier
        stages: [commit]
        exclude: Pipfile.lock

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-s]
        exclude: ^(ansible/|.github/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--skip-glob", "/builds/*"]

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # Python code formatting in code blocks inside docs
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          [
            flake8-bugbear==22.1.11,
            flake8-docstrings==1.6.0,
            pep8-naming==0.13.0,
            pyproject-flake8==0.0.1a2,
          ]
        args:
          - "--max-line-length=100"

  - repo: https://github.com/PyCQA/docformatter.git
    rev: v1.4
    hooks:
      - id: docformatter
        args: ["--in-place"]

  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.5.3
    hooks:
      - id: gitleaks
